
services:
  # nginx:
  #   ports:
  #     - "85:85"
  #     - "443:443"
  #   build:
  #     context: ./Nginx
  #     dockerfile: Dockerfile
  #   depends_on:
  #     authentication:
  #       condition: service_started
  #     nodes:
  #       condition: service_started

  # authentication:
  #   image: authentication
  #   build:
  #     context: ./authentication
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
      
  
  # nodes:
  #   image: node
  #   build:
  #     context: ./nodes
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpwd
      POSTGRES_DB: terralogic
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d terralogic"]
      interval: 5s
      timeout: 5s
      retries: 5

  

volumes:
  postgres: 
    driver: local
  